config/routes.rb
Rails.application.routes.draw do
  root "books#index"
 post '/' =>'books#import', as: 'import'
 get 'info' =>'books#info', as: 'info'

  resources :books

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord



end

app/models/datum.rb
class Datum < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all  

    
    
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  respond_to do |format|
    format.html 
    format.js
  end
      

  end

  # POST /books
  # POST /books.json
  def create

    @book = Book.new(book_params)
 
    respond_to do |format|
      if @book.save
        
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
        format.js { flash[:notice] =  'Book was successfully created.'}

      else

        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
        format.js
      end

    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
        format.js {flash[:notice] =  'Book was successfully updated.'}
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
       format.js   {  flash[:notice] =  'Book was successfully deleted .' }
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def import
    Datum.destroy_all
      u = Datum.create data_params
       load u.attachment.path
           respond_to do |format|
        
      format.html {  redirect_to root_path }
      format.json { head :no_content }
       format.js  
    
    end
    
   end

   def info
      u= Datum.first
      #if u != nil
      @books=Book.all
    if u
      change @books,u.attachment.path
      download u.attachment.path
    end
    #return
    
       
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :phone)
    end

#######################################
      def data_params
      params.require(:'/').permit(:attachment)
   end
 #################################  
   
####################
def load from_file
  line_data={}
  all_data=[]
 File.readlines(from_file).each do |line|
  n, p =line.split(' ')
  line_data[:name] = n
  line_data[:phone] = p
    all_data << line_data
     line_data={}
    end
   
    puts '====================='
    puts line_data
    puts '-------------'
    puts all_data
      unless all_data.empty?
     Book.destroy_all
      end
     all_data.each do |data|
      unless data[:name].blank? or data[:phone].blank?
      Book.create name:data[:name].to_s, phone:data[:phone].to_s
       end
     end 

   all_data
end
####################
def download file
     send_file(file)
end
####################
def change books,filename
  File.open(filename,'w') do |file|
      file.truncate(0)
      books.sort.each do |book|
      file.puts "#{book.name} #{book.phone}"

   end
  end
end
####################

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
   
      <tr>
        <td><%= @book.name %></td>
        <td><%= @book.phone %></td>
        
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'delete' %></td>
      </tr>
  

app/views/books/_form.html.erb
<div id='forma'>
<%= form_for( @book, remote: true, local: true) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/books/_table.html.erb
<table id='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.phone %></td>
        <td><%= link_to 'Edit', edit_book_path(book), remote: true %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: 'delete' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/create.js.erb
$('#forma').remove();
$('#new_link').show();
$('#table').append('<%= j render(@book)%>');


$("#notice").html("<%=j flash[:notice] %>");

app/views/books/destroy.js.erb
$('.delete').bind('ajax:success', function() {     
  $(this).closest('tr').fadeOut();
});

$("#notice").html("<%=j flash[:notice] %>");

$('#forma').remove();
$('#new_link').show();

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/edit.js.erb
$('#forma').hide();
$('#new_link').hide().after('<%= j render 'form'  %>');

$('tr').find('td:first').each(function(){
	if ($(this).text() == '<%= raw @book.name %>'){
	$(this).parent().addClass('edit_row');
  }
});

app/views/books/import.js.erb
 location.reload(true);
$("#notice").remove();

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

 <%= render 'table' %>

<br>

<%= link_to 'New Book', new_book_path, id: 'new_link', remote: true %>
<br><br><br/>
<%= form_for import_path, remote: true, html: { multipart: true } do |f| %>
<%= f.label :attachment, 'only txt files' %>
<%= f.file_field :attachment %>
<%= f.submit 'import' %>
<% end %>

<br/> <br/><br/>
 <%= link_to( 'Get data in a file',info_path,  id: 'download') %> 

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/new.js.erb
$('#new_link').hide().after('<%= j render 'form'  %>');

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @book.phone %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/update.js.erb
$('#forma').remove();
$('#new_link').show();


$('.edit_row').find('td:first').text('<%= raw @book.name %>').next().text('<%= raw @book.phone %>');

$('#table tr').removeClass("edit_row");
$("#notice").html("<%=j flash[:notice] %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>